spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: betta12@gmail.com
    password: ???
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true

server:
  port: 8081

  logging:
    level:
      root: INFO